const taglines = [
  "Not Fooling Anyone, But We Love Them Anyway!",
  "Awkwardly Trying to Fit In, One Bowtie at a Time.",
  "Proving That Being Yourself is the Best Disguise.",
  "Accessorize Like a Blob, Confuse Like a Pro.",
  "Earth’s Newest (and Cutest) Residents",
  "Making Mistakes, One Cute Outfit at a Time.",
  "They Might Be Aliens, But They’re Adorable Ones!",
  "Blobs Are Here, and They’re Totally (Not) Normal.",
  "Earth’s Environmental Heroes in Hilarious Disguises!",
  "Unconventional, Unstoppable, Unmistakably Cute.",
  "Save the Planet, One Silly Outfit at a Time.",
  "Who Needs Shape-Shifting When You Have Accessories?",
  "Adorable Aliens on a Mission to Blend In (Mostly).",
  "Trying to Fit In, One Misstep at a Time.",
  "Fixing Earth, Looking Ridiculous.",
  "Outfits Don’t Make the Blob, But They Sure Are Fun.",
  "Our New Friends Who Don’t Quite Understand Us.",
  "Mixing Up Human Culture, But Making It Cute.",
  "Totally Human... Probably?",
  "They’re Here to Help… and Confuse You.",
  "Saving the World, One Hat at a Time.",
  "Where Environmentalism Meets Fashion Faux Pas.",
  "Let’s Be Honest, They’re Too Cute to Call Out.",
  "Blobs Are Here to Fix Earth... and Look Ridiculous Doing It.",
  "They May Not Fit In, But They Sure Are Charming.",
  "Putting the 'Cute' in 'Unconventional.'",
  "Totally Human? Not Quite, But We’re Trying!",
  "Save the Planet in Style (Or Not)!",
  "The Blobs Are Coming, and They’re Adorably Misunderstood.",
  "Getting the Job Done, One Funny Outfit at a Time.",
  "Attempting to Fit In, While Winning Your Heart.",
  "Fashion Experts (Sort Of).",
  "Helping Earth, One Laughable Look at a Time.",
  "For When You Want to Save the Planet, But Also Look Funny.",
  "Trying to Blend in, but They’re Too Cute to Hide.",
  "Save the Earth, But Make It Silly.",
  "They Might Be Aliens, But We Think They're Kinda Cool.",
  "Outfits May Not Be Perfect, But They Sure Are Fun!",
  "Saving the Environment, One Laugh at a Time.",
  "Learning Human Ways... One Misstep at a Time.",
  "Blobs Are Here! And Yes, They’re Really That Cute.",
  "They’re Blobs, and They’re Here to Stay (With Hats).",
  "Totally Normal (Except for the Bowtie).",
  "Adorable Aliens, Terribly Confused About Fashion.",
  "Proof That Being Different Can Be Cute.",
  "Saving Earth, One Quirky Disguise at a Time.",
  "Weird, Wonderful, and Here to Help.",
  "They Might Be Aliens, But They’ve Got Heart (and Hats).",
  "Totally Earth-Friendly, Totally Fashionably Wrong.",
];

const text = {
  name: "Big Plumpy Blobs!",
  taglines: taglines,
  metaData: {
    homeTitle: "BigPlumpyBlobs",
    homeDescription:
      "Big Plumpy Blobs are here to save the planet, one silly outfit at a time. Collect and trade these adorable aliens on the blockchain!",
    notFoundTitle: "Not Found",
    notFoundDescription: "The page you were looking for could not be found",
  },
  notFound: {
    notFoundTitle1: "Error 404",
    notFoundTitle2: "Page Not Found",
    notFoundBody: "The page you were looking for could not be found",
    notFoundButtonText: "Go Home",
  },
  home: {
    galleryNavText: "Check Gallery",
    openseaNavText: "Start Collecting",
    taglineLoadingText: "Loading...",
    aboutSectionTitle: "Welcome the Big Plumpy Blobs!",
    aboutSectionBody: `The Big Plumpy Blobs crash-landed on Earth, convinced that wearing random accessories makes them perfectly human. After accidentally destroying their homeworld, Gelatopia, they’re determined to save Earth from the same fate—despite their hilariously terrible disguises. Earthlings play along, trading them even sillier outfits, while the blobs do their best to "blend in" and fix the planet… however poorly they interpret both.`,
    loreSectionTitle: "Where did they come from??",
    loreSectionBody: "Learn the Lore of the Blobs!",
    loreSectionButtonText: "Discover",
    gallerySectionTitle: "Meet them all",
    gallerySectionBody:
      "Check out the gallery and meet all the precious blobs.",
    gallerySectionButtonText: "Check Out",
    discordSectionTitle: "Join our Discord Server!",
    discordSectionBody:
      "Join our server for the latest news and events we have going on.",
    discordSectionButtonText: "Join Server",
  },
  mainFooter: {
    socialMediaHeadingText: "Join Us",
    copyrightText: `COPYRIGHT ${new Date().getFullYear()}–All Rights Reserved`,
    legalButtonPrivacyPolicyText: "Privacy Policy",
    legalButtonTermsOfUseText: "Terms of Use",
    legalButtonIPRightsText: "IP Rights",
  },
};

export default text;
